{
 "title": "renterd",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "network", "query": { "query": "renterd_autopilot_state_uptime" } },
   {
    "name": "hosts",
    "query": {
     "query": "renterd_autopilot_state_uptime{network=\"$network\", version=\"$version\", os=\"$os\"}"
    }
   },
   {
    "name": "os",
    "query": {
     "query": "renterd_autopilot_state_uptime{network=\"$network\"}"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "renterd_autopilot_state_uptime{network=\"$network\", os=\"$os\"}"
    }
   },
   {
    "name": "peer",
    "query": {
     "query": "renterd_host_pricetable_validity{instance=\"$hosts\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renterd_consensus_state_chain_index_height{instance=\"$hosts\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "SC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renterd_wallet_spendable{instance=\"$hosts\"} / 1000000000000000000000000"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 17, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "renterd_alert{instance=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "Autopilot Configured",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renterd_autopilot_state_configured{instance=\"$hosts\"} "
    }
   ]
  },
  {
   "title": "Scanning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renterd_autopilot_state_scanning{instance=\"$hosts\"} "
    }
   ]
  },
  {
   "title": "Migrating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renterd_autopilot_state_migrating{instance=\"$hosts\"} "
    }
   ]
  },
  {
   "title": "Average Object Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renterd_objects_avghealth{instance=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "Total Slabs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renterd_slabbuffers_totalslabs{instance=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "Hosts Block Height Leeway",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renterd_upload_settings_hostblockheightleeway{instance=\"$hosts\"}",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Unavailable Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renterd_objects_unavailable{instance=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "Min Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renterd_upload_redundancy_settings_minshards{instance=\"$hosts\"}",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Total Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renterd_upload_redundancy_settings_totalshards{instance=\"$hosts\"}",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Syncer Address",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "targets": [
    {
     "expr": "renterd_syncer_address{instance=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "min(renterd_host_pricetable_hostblockheight > 0)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Scanning Hosts",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "renterd_hosts_scanning{instance=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "Peers Address",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "targets": [
    {
     "expr": "renterd_syncer_address{instance=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "Wallet Num Outputs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renterd_wallet_numoutputs{instance=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "Syncer Peers",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum by (address) (renterd_syncer_peer{instance=\"$hosts\"})"
    }
   ]
  },
  {
   "title": "Allowed Hosts",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "renterd_allowed_host{instance=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "Slab Buffer Total Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renterd_slabbuffers_totalsize{instance=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "Blocked Hosts",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "renterd_blocked_host{instance=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renterd_autopilot_state_uptime{instance=\"$hosts\"} "
    }
   ]
  },
  {
   "title": "Pruning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renterd_autopilot_state_pruning{instance=\"$hosts\"} "
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Storage Used",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 2, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(renterd_host_settings_totalstorage{instance=\"$hosts\"}) - sum(renterd_host_settings_remainingstorage{instance=\"$hosts\"})) / sum(renterd_host_settings_totalstorage{instance=\"$hosts\"})) * 100"
    }
   ]
  },
  {
   "title": "Network Used / Network Capacity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 2, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(renterd_host_settings_totalstorage{instance=\"$hosts\"})",
     "legendFormat": "Total Storage"
    },
    {
     "expr": "sum(renterd_host_settings_remainingstorage{instance=\"$hosts\"})",
     "legendFormat": "Remaining Storage"
    },
    {
     "expr": "sum(renterd_host_settings_totalstorage{instance=\"$hosts\"}) - sum(renterd_host_settings_remainingstorage{instance=\"$hosts\"})",
     "legendFormat": "Used Storage"
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(renterd_host_settings_totalstorage{instance=\"$hosts\"})"
    }
   ]
  },
  {
   "title": "DL Bandwidth Cost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "fSC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(renterd_host_pricetable_downloadbandwidthcost{instance=\"$hosts\"} / 10000000000000)"
    }
   ]
  },
  {
   "title": "% Accepting Contracts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(renterd_host_settings_acceptingcontracts{instance=\"$hosts\"} == 1) / (sum(renterd_host_settings_acceptingcontracts{instance=\"$hosts\"} == 0) + sum(renterd_host_settings_acceptingcontracts{instance=\"$hosts\"} == 1)) * 100"
    }
   ]
  },
  {
   "title": "% Scanned",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(renterd_host_scanned{instance=\"$hosts\"} == 1) / (sum(renterd_host_scanned{instance=\"$hosts\"} == 0) + sum(renterd_host_scanned{instance=\"$hosts\"} == 1)) * 100"
    }
   ]
  },
  {
   "title": "Contract Price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "mSC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(renterd_host_pricetable_contractprice{instance=\"$hosts\"} / 1000000000000000000000)"
    }
   ]
  },
  {
   "title": "Storage Price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "aSC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(renterd_host_settings_storageprice{instance=\"$hosts\"} / 100000000000)"
    }
   ]
  },
  {
   "title": "Base RPC Price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "pSC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(renterd_host_settings_baserpcprice{instance=\"$hosts\"} / 1000000000000000)"
    }
   ]
  },
  {
   "title": "Collateral Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "aSC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(renterd_host_pricetable_collateralcost{instance=\"$hosts\"} / 100000000000)"
    }
   ]
  },
  {
   "title": "Max Collateral",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "SC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(renterd_host_pricetable_maxcollateral{instance=\"$hosts\"} / 1000000000000000000000000)"
    }
   ]
  },
  {
   "title": "UL Bandwidth Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "fSC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(renterd_host_pricetable_uploadbandwidthcost{instance=\"$hosts\"} / 10000000000000)"
    }
   ]
  },
  {
   "title": "Peer Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Storage",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_settings_totalstorage{instance=\"$hosts\", netAddress=\"$peer\"}"
      }
     ]
    },
    {
     "title": "Accepting Contracts",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 2, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_settings_acceptingcontracts{instance=\"$hosts\", netAddress=\"$peer\"}"
      }
     ]
    },
    {
     "title": "Init Base Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "nSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_initbasecost{instance=\"$hosts\", netAddress=\"$peer\"} / 100000000000000000)"
      }
     ]
    },
    {
     "title": "Sector Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_settings_sectorsize{instance=\"$hosts\", netAddress=\"$peer\"}"
      }
     ]
    },
    {
     "title": "Base RPC Price",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "pSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_settings_baserpcprice{instance=\"$hosts\", netAddress=\"$peer\"} / 1000000000000000"
      }
     ]
    },
    {
     "title": "Tx Fee Min Recommend",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ÂµSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_txnfeeminrecommended{instance=\"$hosts\", netAddress=\"$peer\"} / 10000000000000000000)"
      }
     ]
    },
    {
     "title": "Ephemeral Acct Expiry",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "hr" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_settings_ephemeralaccountexpiry{instance=\"$hosts\", netAddress=\"$peer\"} / 3600000"
      }
     ]
    },
    {
     "title": "Write Length Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "H" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_writelengthcost{instance=\"$hosts\", netAddress=\"$peer\"})"
      }
     ]
    },
    {
     "title": "Max Collateral",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_maxcollateral{instance=\"$hosts\", netAddress=\"$peer\"} / 1000000000000000000000000)"
      }
     ]
    },
    {
     "title": "Storage Price",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "aSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_settings_storageprice{instance=\"$hosts\", netAddress=\"$peer\"} / 100000000000"
      }
     ]
    },
    {
     "title": "DL Bandwidth Cost",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 2, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "fSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_downloadbandwidthcost{instance=\"$hosts\", netAddress=\"$peer\"} / 10000000000000)"
      }
     ]
    },
    {
     "title": "Max Duration",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "sec" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_maxduration{instance=\"$hosts\", netAddress=\"$peer\"} / 1000)"
      }
     ]
    },
    {
     "title": "Window Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_settings_windowsize{instance=\"$hosts\", netAddress=\"$peer\"}"
      }
     ]
    },
    {
     "title": "Collateral Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "aSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_collateralcost{instance=\"$hosts\", netAddress=\"$peer\"} / 100000000000)"
      }
     ]
    },
    {
     "title": "Tx Fee Min Recommend",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ÂµSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_txnfeemaxrecommended{instance=\"$hosts\", netAddress=\"$peer\"} / 10000000000000000000)"
      }
     ]
    },
    {
     "title": "Revision Number",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_settings_revisionnumber{instance=\"$hosts\", netAddress=\"$peer\"}"
      }
     ]
    },
    {
     "title": "Read Length Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "H" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_readlengthcost{instance=\"$hosts\", netAddress=\"$peer\"})"
      }
     ]
    },
    {
     "title": "Storage Used",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 2, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((renterd_host_settings_totalstorage{instance=\"$hosts\", netAddress=\"$peer\"} - renterd_host_settings_remainingstorage{instance=\"$hosts\", netAddress=\"$peer\"}) / renterd_host_settings_totalstorage{instance=\"$hosts\", netAddress=\"$peer\"}) * 100"
      }
     ]
    },
    {
     "title": "Max Ephemeral Account Balance",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_settings_maxephemeralaccountbalance{instance=\"$hosts\", netAddress=\"$peer\"} / 1000000000000000000000000"
      }
     ]
    },
    {
     "title": "Revision Base Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "H" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_revisionbasecost{instance=\"$hosts\", netAddress=\"$peer\"})"
      }
     ]
    },
    {
     "title": "Renew Contract Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 13, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "nSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_renewcontractcost{instance=\"$hosts\", netAddress=\"$peer\"} / 100000000000000000)"
      }
     ]
    },
    {
     "title": "Max Revision Batch Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_settings_maxrevisebatchsize{instance=\"$hosts\", netAddress=\"$peer\"} / 1000"
      }
     ]
    },
    {
     "title": "Sub Notification Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "H" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_subscriptionmemorycost{instance=\"$hosts\", netAddress=\"$peer\"})"
      }
     ]
    },
    {
     "title": "Registry Free",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 2, "x": 22, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(renterd_host_pricetable_registryentriesleft{instance=\"$hosts\", netAddress=\"$peer\"} / renterd_host_pricetable_registryentriestotal{instance=\"$hosts\", netAddress=\"$peer\"}) * 100"
      }
     ]
    },
    {
     "title": "UL Bandwidth Cost",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 2, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "fSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_uploadbandwidthcost{instance=\"$hosts\", netAddress=\"$peer\"} / 10000000000000)"
      }
     ]
    },
    {
     "title": "Read Base Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "nSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_readbasecost{instance=\"$hosts\", netAddress=\"$peer\"} / 100000000000000000)"
      }
     ]
    },
    {
     "title": "Write Base Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "nSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_writebasecost{instance=\"$hosts\", netAddress=\"$peer\"} / 100000000000000000)"
      }
     ]
    },
    {
     "title": "Latest Revision Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "nSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_latestrevisioncost{instance=\"$hosts\", netAddress=\"$peer\"} / 100000000000000000)",
       "legendFormat": "{{ uid }}"
      }
     ]
    },
    {
     "title": "Memory Time Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 13, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "H" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_memorytimecost{instance=\"$hosts\", netAddress=\"$peer\"})"
      }
     ]
    },
    {
     "title": "Max Download Batch Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_settings_maxdownloadbatchsize{instance=\"$hosts\", netAddress=\"$peer\"}"
      }
     ]
    },
    {
     "title": "Account Balance Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "H" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_accountbalancecost{instance=\"$hosts\", netAddress=\"$peer\"})"
      }
     ]
    },
    {
     "title": "Contract Price",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 2, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "mSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_contractprice{instance=\"$hosts\", netAddress=\"$peer\"} / 1000000000000000000000)"
      }
     ]
    },
    {
     "title": "Price Table Validity",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 6, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_validity{instance=\"$hosts\", netAddress=\"$peer\"} / 60000)"
      }
     ]
    },
    {
     "title": "Fund Account Cost",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "H" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_fundaccountcost{instance=\"$hosts\", netAddress=\"$peer\"})"
      }
     ]
    },
    {
     "title": "Has Sector Base Cost",
     "type": "stat",
     "gridPos": { "h": 2, "w": 9, "x": 13, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_hassectorbasecost{instance=\"$hosts\", netAddress=\"$peer\"})"
      }
     ]
    },
    {
     "title": "Update Price Table Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "H" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_updatepricetablecost{instance=\"$hosts\", netAddress=\"$peer\"})"
      }
     ]
    },
    {
     "title": "Drop Sectors Base Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 13, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "H" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_dropsectorsbasecost{instance=\"$hosts\", netAddress=\"$peer\"})"
      }
     ]
    },
    {
     "title": "Swap Sector Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "H" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_swapsectorcost{instance=\"$hosts\", netAddress=\"$peer\"})"
      }
     ]
    },
    {
     "title": "Drop Sectors Unit Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "H" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_host_pricetable_dropsectorsunitcost{instance=\"$hosts\", netAddress=\"$peer\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Download Avail",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_worker_memory_download_available{instance=\"$hosts\"}"
      }
     ]
    },
    {
     "title": "Memory Upload Avail",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_worker_memory_upload_available{instance=\"$hosts\"}"
      }
     ]
    },
    {
     "title": "Avg DL Speed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_worker_stats_avgdownloadspeedmbps{instance=\"$hosts\"}"
      }
     ]
    },
    {
     "title": "Avg Overdrive % DL",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_worker_stats_avgoverdrivepct_download{instance=\"$hosts\"}"
      }
     ]
    },
    {
     "title": "# Downloaders",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_worker_stats_numdownloaders{instance=\"$hosts\"}"
      }
     ]
    },
    {
     "title": "Healthy Downloaders",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_worker_stats_healthydownloaders{instance=\"$hosts\"}"
      }
     ]
    },
    {
     "title": "Memory Download Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_worker_memory_download_total{instance=\"$hosts\"}"
      }
     ]
    },
    {
     "title": "Memory Upload Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_worker_memory_upload_total{instance=\"$hosts\"}"
      }
     ]
    },
    {
     "title": "Avg UL Speed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_worker_stats_avgslabuploadspeedmbps{instance=\"$hosts\"}"
      }
     ]
    },
    {
     "title": "Avg Overdrive % UL",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_worker_stats_avgoverdrivepct_upload{instance=\"$hosts\"}"
      }
     ]
    },
    {
     "title": "# Uploaders",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_worker_stats_numuploaders{instance=\"$hosts\"}"
      }
     ]
    },
    {
     "title": "Healthy Uploaders",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_worker_stats_healthyuploaders{instance=\"$hosts\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pricing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Upload Price",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_upload_settings_maxuploadprice{instance=\"$hosts\"} / 1000000000000000000000000",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "TODO Max Storage Price",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_upload_settings_maxstorageprice{instance=\"$hosts\"} / 1000000000",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Min max collateral",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_upload_settings_minmaxcollateral{instance=\"$hosts\"} / 1000000000000000000000000",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Max Download Price",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_upload_settings_maxdownloadprice{instance=\"$hosts\"} / 1000000000000000000000000",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Min Max Ephemeral Account Balance",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_upload_settings_minmaxephemeralaccountbalance{instance=\"$hosts\"} / 1000000000000000000000000",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Migration Surcharge Multiplier",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_upload_settings_migrationsurchargemultiplier{instance=\"$hosts\"}",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Min Price Table Validity",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(renterd_upload_settings_minpricetablevalidity{instance=\"$hosts\"} / 60000)",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Min Account Expiry",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "hr" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_upload_settings_minaccountexpiry{instance=\"$hosts\"} / 60000 / 60",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Setting - Incl Redundancy Max Upload Price",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_settings_include_redundancy_maxuploadprice{instance=\"$hosts\"}"
      }
     ]
    },
    {
     "title": "Setting - Incl Redundancy Max Storage Price",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_settings_include_redundancy_maxstorageprice{instance=\"$hosts\"}"
      }
     ]
    },
    {
     "title": "Max Contract Price",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_upload_settings_maxcontractprice{instance=\"$hosts\"} / 1000000000000000000000000",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Max RPC Price",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 9, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "SC/million" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_upload_settings_maxrpcprice{instance=\"$hosts\"} / 1000000000000000000",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Upload Transaction Fee",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "mSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_upload_transactionfee{instance=\"$hosts\"} / 1000000000000000000000"
      }
     ]
    },
    {
     "title": "Recommended Txn Fee",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "mSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_tpool_fee{instance=\"$hosts\"} / 1000000000000000000000"
      }
     ]
    }
   ]
  },
  {
   "title": "Contracts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Contracts",
     "type": "table",
     "gridPos": { "h": 12, "w": 20, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "targets": [
      {
       "expr": "renterd_contract{instance=\"$hosts\"} / 1000000000000000000000000"
      }
     ]
    },
    {
     "title": "Prunable Contracts",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_prunable_contracts_total{instance=\"$hosts\"}  "
      }
     ]
    },
    {
     "title": "Prunable Size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_prunable_contracts_size{instance=\"$hosts\"}  "
      }
     ]
    }
   ]
  },
  {
   "title": "Interactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scanned",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_scanned{instance=\"$hosts\", netAddress=\"$peer\"} "
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 3, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_interactions_uptime{instance=\"$hosts\", netAddress=\"$peer\"}"
      }
     ]
    },
    {
     "title": "Total Scans",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_interactions_totalscans{instance=\"$hosts\", netAddress=\"$peer\"}"
      }
     ]
    },
    {
     "title": "Second To Last Scan Success",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_interactions_secondtolastscansuccess{instance=\"$hosts\", netAddress=\"$peer\"} "
      }
     ]
    },
    {
     "title": "Failed Interactions",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_interactions_failedinteractions{instance=\"$hosts\", netAddress=\"$peer\"}"
      }
     ]
    },
    {
     "title": "Downtime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 3, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_interactions_downtime{instance=\"$hosts\", netAddress=\"$peer\"}"
      }
     ]
    },
    {
     "title": "Lost Sectors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_interactions_lostsectors{instance=\"$hosts\", netAddress=\"$peer\"}"
      }
     ]
    },
    {
     "title": "Last Scan Success",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_interactions_lastscansuccess{instance=\"$hosts\", netAddress=\"$peer\"}"
      }
     ]
    },
    {
     "title": "Successfull Interactions",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_host_interactions_successfulinteractions{instance=\"$hosts\", netAddress=\"$peer\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num Tx TxPool",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_txpool_numtxns{instance=\"$hosts\"}",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Num Finished Objects",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_stats_numunfinishedobjects{instance=\"$hosts\"}",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Num Objects",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_stats_numobjects{instance=\"$hosts\"}",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Min Health",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_stats_minhealth{instance=\"$hosts\"}",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Total Object Size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_stats_totalobjectsize{instance=\"$hosts\"}",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Total Unfinished Obj Size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_stats_totalunfinishedobjectssize{instance=\"$hosts\"}",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Total Sector Size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_stats_totalsectorssize{instance=\"$hosts\"}",
       "legendFormat": "balance"
      }
     ]
    },
    {
     "title": "Total Uploaded Size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "renterd_stats_totaluploadedsize{instance=\"$hosts\"}",
       "legendFormat": "balance"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "renterd_wallet_transaction_total{instance=\"$hosts\"} / 1000000000000000000000"
      }
     ]
    }
   ]
  }
 ]
}