{
 "title": "hostd",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "network", "query": { "query": "hostd_host_state" } },
   {
    "name": "hostdhost",
    "query": {
     "query": "hostd_host_state{network=\"$network\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "SC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hostd_metrics_balance{instance=\"$hostdhost\"}",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "table",
   "gridPos": { "h": 18, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "hostd_wallet_transaction{instance=\"$hostdhost\"}"
    }
   ]
  },
  {
   "title": "Syncer Peers",
   "type": "table",
   "gridPos": { "h": 18, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by (address) (hostd_syncer_peer{instance=\"$hostdhost\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "hostd_alert{instance=\"$hostdhost\"}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hostd_consensus_state_index{instance=\"$hostdhost\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (hostd_syncer_peer{instance=\"$hostdhost\"})"
    }
   ]
  },
  {
   "title": "Net Address",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "targets": [
    {
     "expr": "hostd_settings_revision{instance=\"$hostdhost\"}"
    }
   ]
  },
  {
   "title": "Syncer Address",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "targets": [
    {
     "expr": "hostd_syncer_address{instance=\"$hostdhost\"}"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Earned",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(hostd_metrics_revenue_earned_rpc{instance=\"$hostdhost\"} + hostd_metrics_revenue_earned_storage{instance=\"$hostdhost\"} + hostd_metrics_revenue_earned_ingress{instance=\"$hostdhost\"} + hostd_metrics_revenue_earned_egress{instance=\"$hostdhost\"} + hostd_metrics_revenue_earned_registry_read{instance=\"$hostdhost\"} + hostd_metrics_revenue_earned_registry_write{instance=\"$hostdhost\"})"
      }
     ]
    },
    {
     "title": "Potential",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(hostd_metrics_revenue_potential_rpc{instance=\"$hostdhost\"} + hostd_metrics_revenue_potential_storage{instance=\"$hostdhost\"} + hostd_metrics_revenue_potential_ingress{instance=\"$hostdhost\"} + hostd_metrics_revenue_potential_egress{instance=\"$hostdhost\"} + hostd_metrics_revenue_potential_registry_read{instance=\"$hostdhost\"} + hostd_metrics_revenue_potential_registry_write{instance=\"$hostdhost\"})"
      }
     ]
    },
    {
     "title": "Storage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_revenue_earned_storage{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Egress",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_revenue_earned_egress{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Ingress",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_revenue_earned_ingress{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Revenue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "delta(hostd_metrics_revenue_earned_rpc{instance=\"$hostdhost\"}[5m])",
       "legendFormat": "earned rpc"
      },
      {
       "expr": "delta(hostd_metrics_revenue_earned_storage{instance=\"$hostdhost\"}[5m])",
       "legendFormat": "earned storage"
      },
      {
       "expr": "delta(hostd_metrics_revenue_earned_ingress{instance=\"$hostdhost\"}[5m])",
       "legendFormat": "earned ingress"
      },
      {
       "expr": "delta(hostd_metrics_revenue_earned_egress{instance=\"$hostdhost\"}[5m])",
       "legendFormat": "earned egress"
      },
      {
       "expr": "delta(hostd_metrics_revenue_potential_rpc{instance=\"$hostdhost\"}[5m])",
       "legendFormat": "potential rpc"
      },
      {
       "expr": "delta(hostd_metrics_revenue_potential_storage{instance=\"$hostdhost\"}[5m])",
       "legendFormat": "potential storage"
      },
      {
       "expr": "delta(hostd_metrics_revenue_potential_ingress{instance=\"$hostdhost\"}[5m])",
       "legendFormat": "potential ingress"
      },
      {
       "expr": "delta(hostd_metrics_revenue_potential_egress{instance=\"$hostdhost\"}[5m])",
       "legendFormat": "potential egress"
      }
     ]
    }
   ]
  },
  {
   "title": "Collateral",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locked",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_contracts_locked_collateral{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Risked",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_contracts_risked_collateral{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Collateral",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "hostd_metrics_contracts_locked_collateral{instance=\"$hostdhost\"}",
       "legendFormat": "locked"
      },
      {
       "expr": "hostd_metrics_contracts_risked_collateral{instance=\"$hostdhost\"}",
       "legendFormat": " risked"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Physical",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_storage_physical_used_bytes{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Storage Used",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 20, "x": 4, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_volume_used_sectors{instance=\"$hostdhost\"} / hostd_volume_total_sectors{instance=\"$hostdhost\"} * 100",
       "legendFormat": "{{ local_path }}"
      }
     ]
    },
    {
     "title": "Reads",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 4, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(hostd_volume_successful_reads{instance=\"$hostdhost\"}[5m])",
       "legendFormat": "{{ local_path }}"
      }
     ]
    },
    {
     "title": "Writes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 9, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(hostd_volume_successful_writes{instance=\"$hostdhost\"}[5m])"
      }
     ]
    },
    {
     "title": "Failed reads",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 14, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(hostd_volume_failed_reads{instance=\"$hostdhost\"}[5m])",
       "legendFormat": "{{ local_path }}"
      }
     ]
    },
    {
     "title": "Failed writes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(hostd_volume_failed_writes{instance=\"$hostdhost\"}[5m])",
       "legendFormat": "{{ local_path }}"
      }
     ]
    },
    {
     "title": "Storage ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "hostd_metrics_storage_contract_sectors{instance=\"$hostdhost\"} * 0.0041849148418491",
       "legendFormat": "sectors contract"
      },
      {
       "expr": "hostd_metrics_storage_physical_sectors{instance=\"$hostdhost\"} * 0.0041849148418491",
       "legendFormat": "sectors physical"
      },
      {
       "expr": "hostd_metrics_storage_temp_sectors{instance=\"$hostdhost\"}",
       "legendFormat": "sectors temp"
      },
      {
       "expr": "hostd_metrics_registry_entries{instance=\"$hostdhost\"} * 113",
       "legendFormat": "registry (max)"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Reads",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(hostd_metrics_storage_reads{instance=\"$hostdhost\"}[5m])"
      }
     ]
    },
    {
     "title": "Storage Writes",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(hostd_metrics_storage_writes{instance=\"$hostdhost\"}[5m])"
      }
     ]
    },
    {
     "title": "Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "delta(hostd_metrics_storage_reads{instance=\"$hostdhost\"}[30m])",
       "legendFormat": "storage read"
      },
      {
       "expr": "delta(hostd_metrics_storage_writes{instance=\"$hostdhost\"}[30m])",
       "legendFormat": "storage write"
      },
      {
       "expr": "delta(hostd_metrics_registry_reads{instance=\"$hostdhost\"}[30m])",
       "legendFormat": "registry reads"
      },
      {
       "expr": "delta(hostd_metrics_registry_writes{instance=\"$hostdhost\"}[30m])",
       "legendFormat": "registry writes"
      }
     ]
    }
   ]
  },
  {
   "title": "Contracts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active contracts",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_contracts_active{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Successfull contracts",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_contracts_successful{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Failed contracts",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_contracts_failed{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Contracts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "hostd_metrics_contracts_successful{instance=\"$hostdhost\"}",
       "legendFormat": "successful"
      },
      {
       "expr": "hostd_metrics_contracts_active{instance=\"$hostdhost\"}",
       "legendFormat": "active"
      },
      {
       "expr": "hostd_metrics_contracts_pending{instance=\"$hostdhost\"}",
       "legendFormat": "pending"
      },
      {
       "expr": "hostd_metrics_contracts_rejected{instance=\"$hostdhost\"}",
       "legendFormat": "rejected"
      },
      {
       "expr": "hostd_metrics_contracts_failed{instance=\"$hostdhost\"}",
       "legendFormat": "failed"
      }
     ]
    }
   ]
  },
  { "title": "Pricing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "SC/TB/month" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(hostd_metrics_pricing_storage_price{instance=\"$hostdhost\"} * 43) / 10000000000"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "SC/tb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hostd_metrics_pricing_ingress_price{instance=\"$hostdhost\"}"
    }
   ]
  },
  {
   "title": "Egress",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "SC/tb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hostd_metrics_pricing_egress_price{instance=\"$hostdhost\"} / 1000000000000"
    }
   ]
  },
  {
   "title": "Collateral",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "SC/tb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((hostd_metrics_pricing_storage_price{instance=\"$hostdhost\"} * 43) / 10000000000) * hostd_settings_collateral_multiplier{instance=\"$hostdhost\"}"
    }
   ]
  },
  {
   "title": "Contract",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "mSC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hostd_metrics_pricing_contract_price{instance=\"$hostdhost\"} / 1000000000000000000000"
    }
   ]
  },
  {
   "title": "Sector Access",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "mSC / million" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hostd_metrics_pricing_sector_access_price{instance=\"$hostdhost\"} / 1000000000000000"
    }
   ]
  },
  {
   "title": "Base RPC",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "mSC / million" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hostd_metrics_pricing_baserpc_price{instance=\"$hostdhost\"} / 1000000000000000"
    }
   ]
  },
  {
   "title": "Pricing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "(hostd_metrics_pricing_storage_price{instance=\"$hostdhost\"} * 43) / 10000000000",
     "legendFormat": "storage"
    },
    {
     "expr": "hostd_metrics_pricing_ingress_price{instance=\"$hostdhost\"} / 1000000000000",
     "legendFormat": "ingress"
    },
    {
     "expr": "hostd_metrics_pricing_egress_price{instance=\"$hostdhost\"} / 1000000000000",
     "legendFormat": "egress"
    },
    {
     "expr": "((hostd_settings_max_collateral{instance=\"$hostdhost\"} / 1000000000000000000000000) / 30) * 10",
     "legendFormat": "collateral"
    },
    {
     "expr": "hostd_metrics_pricing_contract_price{instance=\"$hostdhost\"} / 1000000000000000000000",
     "legendFormat": "contract"
    },
    {
     "expr": "hostd_metrics_pricing_sector_access_price{instance=\"$hostdhost\"} / 100000000000000000",
     "legendFormat": "sector access"
    },
    {
     "expr": "hostd_metrics_pricing_baserpc_price{instance=\"$hostdhost\"} / 100000000000000000",
     "legendFormat": "rpc"
    }
   ]
  }
 ]
}