{
 "title": "walletd",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hosts",
    "query": {
     "query": "walletd_consensus_network{network=\"$network\"}"
    }
   },
   { "name": "network", "query": { "query": "walletd_consensus_network" } },
   {
    "name": "wallets",
    "query": {
     "query": "walletd_wallet_balance_siacoins"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "SC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walletd_wallet_balance_siacoins{instance=\"$hosts\"} / 1000000000000000000000000"
    }
   ]
  },
  {
   "title": "Sia Funds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "SF" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walletd_wallet_balance_siafunds{instance=\"$hosts\"}  "
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "table",
   "gridPos": { "h": 20, "w": 13, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "+walletd_wallet_event_transaction_total{instance=\"$hosts\"} / 1000000000000000000000"
    }
   ]
  },
  {
   "title": "Syncer Peers",
   "type": "table",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "expr": "walletd_syncer_peer{instance=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walletd_consensus_tip_height{instance=\"$hosts\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "TxPool Fee",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mSC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walletd_txpool_fee{instance=\"$hosts\"} / 1000000000000000000000"
    }
   ]
  },
  {
   "title": "TxPool Num Txns v1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walletd_txpool_numtxns_v1{instance=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "TxPool Num Txns v2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walletd_txpool_numtxns_v2{instance=\"$hosts\"}"
    }
   ]
  }
 ]
}