{
 "title": "hostdash",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostdhost",
    "query": {
     "query": "hostd_host_state{network=\"$network\"}"
    }
   },
   { "name": "network", "query": { "query": "hostd_host_state" } }
  ]
 },
 "panels": [
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Height",
     "type": "stat",
     "gridPos": { "h": 17, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_consensus_state_chain_index_height{instance=\"$hostdhost\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Balance",
     "type": "stat",
     "gridPos": { "h": 17, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_balance{instance=\"$hostdhost\"} / 1000000000000000000000000"
      }
     ]
    },
    {
     "title": "Alerts",
     "type": "table",
     "gridPos": { "h": 17, "w": 4, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "hostd_alert{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "table",
     "gridPos": { "h": 17, "w": 4, "x": 20, "y": 1 },
     "targets": [
      {
       "expr": "hostd_wallet_transaction_total{instance=\"$hostdhost\"} / 1000000000000000000000000"
      }
     ]
    },
    {
     "title": "Syncer Peers",
     "type": "table",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum by (address) (hostd_syncer_peer{instance=\"$hostdhost\"})"
      }
     ]
    },
    {
     "title": "Connected Peers",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (hostd_syncer_peer{instance=\"$hostdhost\"})"
      }
     ]
    },
    {
     "title": "Syncer Address",
     "type": "table",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
     "targets": [
      {
       "expr": "hostd_syncer_address{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Net Address",
     "type": "table",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 22 },
     "targets": [
      {
       "expr": "hostd_settings_revision{instance=\"$hostdhost\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Earned",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(hostd_metrics_revenue_earned_rpc{instance=\"$hostdhost\"} + hostd_metrics_revenue_earned_storage{instance=\"$hostdhost\"} + hostd_metrics_revenue_earned_ingress{instance=\"$hostdhost\"} + hostd_metrics_revenue_earned_egress{instance=\"$hostdhost\"} + hostd_metrics_revenue_earned_registry_read{instance=\"$hostdhost\"} + hostd_metrics_revenue_earned_registry_write{instance=\"$hostdhost\"}) / 1000000000000000000000000"
      }
     ]
    },
    {
     "title": "Potential",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(hostd_metrics_revenue_potential_rpc{instance=\"$hostdhost\"} + hostd_metrics_revenue_potential_storage{instance=\"$hostdhost\"} + hostd_metrics_revenue_potential_ingress{instance=\"$hostdhost\"} + hostd_metrics_revenue_potential_egress{instance=\"$hostdhost\"} + hostd_metrics_revenue_potential_registry_read{instance=\"$hostdhost\"} + hostd_metrics_revenue_potential_registry_write{instance=\"$hostdhost\"}) / 1000000000000000000000000"
      }
     ]
    },
    {
     "title": "Storage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_revenue_earned_storage{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Egress",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_revenue_earned_egress{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Ingress",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_revenue_earned_ingress{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Registry Read",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_revenue_earned_registry_read{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Registry Write",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_revenue_earned_registry_write{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Revenue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "(hostd_metrics_revenue_earned_rpc{instance=\"$hostdhost\"} + hostd_metrics_revenue_earned_storage{instance=\"$hostdhost\"} + hostd_metrics_revenue_earned_ingress{instance=\"$hostdhost\"} + hostd_metrics_revenue_earned_egress{instance=\"$hostdhost\"} + hostd_metrics_revenue_earned_registry_read{instance=\"$hostdhost\"} + hostd_metrics_revenue_earned_registry_write{instance=\"$hostdhost\"}) / 1000000000000000000000000",
       "legendFormat": "earned total"
      },
      {
       "expr": "hostd_metrics_revenue_earned_rpc{instance=\"$hostdhost\"}",
       "legendFormat": "earned rpc"
      },
      {
       "expr": "hostd_metrics_revenue_earned_storage{instance=\"$hostdhost\"}",
       "legendFormat": "earned storage"
      },
      {
       "expr": "hostd_metrics_revenue_earned_ingress{instance=\"$hostdhost\"}",
       "legendFormat": "earned ingress"
      },
      {
       "expr": "hostd_metrics_revenue_earned_egress{instance=\"$hostdhost\"}",
       "legendFormat": "earned egress"
      },
      {
       "expr": "hostd_metrics_revenue_earned_registry_read{instance=\"$hostdhost\"}",
       "legendFormat": "earned registry reads"
      },
      {
       "expr": "hostd_metrics_revenue_earned_registry_write{instance=\"$hostdhost\"}",
       "legendFormat": "earned registry writes"
      },
      {
       "expr": "(hostd_metrics_revenue_potential_rpc{instance=\"$hostdhost\"} + hostd_metrics_revenue_potential_storage{instance=\"$hostdhost\"} + hostd_metrics_revenue_potential_ingress{instance=\"$hostdhost\"} + hostd_metrics_revenue_potential_egress{instance=\"$hostdhost\"} + hostd_metrics_revenue_potential_registry_read{instance=\"$hostdhost\"} + hostd_metrics_revenue_potential_registry_write{instance=\"$hostdhost\"}) / 1000000000000000000000000",
       "legendFormat": "potential total"
      },
      {
       "expr": "hostd_metrics_revenue_potential_rpc{instance=\"$hostdhost\"} / 1000000000000000000000000",
       "legendFormat": "potential rpc"
      },
      {
       "expr": "hostd_metrics_revenue_potential_storage{instance=\"$hostdhost\"} / 1000000000000000000000000",
       "legendFormat": "potential storage"
      },
      {
       "expr": "hostd_metrics_revenue_potential_ingress{instance=\"$hostdhost\"} / 1000000000000000000000000",
       "legendFormat": "potential ingress"
      },
      {
       "expr": "hostd_metrics_revenue_potential_egress{instance=\"$hostdhost\"} / 1000000000000000000000000",
       "legendFormat": "potential egress"
      },
      {
       "expr": "hostd_metrics_revenue_potential_registry_read{instance=\"$hostdhost\"}",
       "legendFormat": "potential registry reads"
      },
      {
       "expr": "hostd_metrics_revenue_potential_registry_write{instance=\"$hostdhost\"}",
       "legendFormat": "potential registry writes"
      }
     ]
    }
   ]
  },
  {
   "title": "Collateral",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locked",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_contracts_locked_collateral{instance=\"$hostdhost\"} / 1000000000000000000000000"
      }
     ]
    },
    {
     "title": "Risked",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "SC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_contracts_risked_collateral{instance=\"$hostdhost\"} / 1000000000000000000000000"
      }
     ]
    },
    {
     "title": "Collateral",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "hostd_metrics_contracts_locked_collateral{instance=\"$hostdhost\"} / 1000000000000000000000000",
       "legendFormat": "locked"
      },
      {
       "expr": "hostd_metrics_contracts_risked_collateral{instance=\"$hostdhost\"} / 1000000000000000000000000",
       "legendFormat": " risked"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Physical",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_storage_physical_sectors{instance=\"$hostdhost\"} * 0.0041849148418491"
      }
     ]
    },
    {
     "title": "Registry",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_registry_entries{instance=\"$hostdhost\"} * 113"
      }
     ]
    },
    {
     "title": "Storage ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "hostd_metrics_storage_contract_sectors{instance=\"$hostdhost\"} * 0.0041849148418491",
       "legendFormat": "sectors contract"
      },
      {
       "expr": "hostd_metrics_storage_physical_sectors{instance=\"$hostdhost\"} * 0.0041849148418491",
       "legendFormat": "sectors physical"
      },
      {
       "expr": "hostd_metrics_storage_temp_sectors{instance=\"$hostdhost\"}",
       "legendFormat": "sectors temp"
      },
      {
       "expr": "hostd_metrics_registry_entries{instance=\"$hostdhost\"} * 113",
       "legendFormat": "registry (max)"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Reads",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_storage_reads{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Storage Writes",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_storage_writes{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Registry Reads",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_registry_reads{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Registry Writes",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_registry_writes{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "hostd_metrics_storage_reads{instance=\"$hostdhost\"}",
       "legendFormat": "storage read"
      },
      {
       "expr": "hostd_metrics_storage_writes{instance=\"$hostdhost\"}",
       "legendFormat": "storage write"
      },
      {
       "expr": "hostd_metrics_registry_reads{instance=\"$hostdhost\"}",
       "legendFormat": "registry reads"
      },
      {
       "expr": "hostd_metrics_registry_writes{instance=\"$hostdhost\"}",
       "legendFormat": "registry writes"
      }
     ]
    }
   ]
  },
  {
   "title": "Contracts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active contracts",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_contracts_active{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Successfull contracts",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_contracts_successful{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Failed contracts",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_contracts_failed{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Contracts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "hostd_metrics_contracts_successful{instance=\"$hostdhost\"}",
       "legendFormat": "successful"
      },
      {
       "expr": "hostd_metrics_contracts_active{instance=\"$hostdhost\"}",
       "legendFormat": "active"
      },
      {
       "expr": "hostd_metrics_contracts_pending{instance=\"$hostdhost\"}",
       "legendFormat": "pending"
      },
      {
       "expr": "hostd_metrics_contracts_rejected{instance=\"$hostdhost\"}",
       "legendFormat": "rejected"
      },
      {
       "expr": "hostd_metrics_contracts_failed{instance=\"$hostdhost\"}",
       "legendFormat": "failed"
      },
      {
       "expr": "hostd_metrics_contracts_successful{instance=\"$hostdhost\"} + hostd_metrics_contracts_active{instance=\"$hostdhost\"} + hostd_metrics_contracts_pending{instance=\"$hostdhost\"} + hostd_metrics_contracts_rejected{instance=\"$hostdhost\"} + hostd_metrics_contracts_failed{instance=\"$hostdhost\"}",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "Pricing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "SC/TB/month" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(hostd_settings_storage_price{instance=\"$hostdhost\"} * 43) / 10000000000"
      }
     ]
    },
    {
     "title": "Ingress",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "SC/tb" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_pricing_ingress_price{instance=\"$hostdhost\"} / 1000000000000"
      }
     ]
    },
    {
     "title": "Egress",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 7, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "SC/tb" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_pricing_egress_price{instance=\"$hostdhost\"} / 1000000000000"
      }
     ]
    },
    {
     "title": "Collateral",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 10, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "SC/tb" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((hostd_settings_storage_price{instance=\"$hostdhost\"} * 43) / 10000000000) * hostd_settings_collateral_multiplier{instance=\"$hostdhost\"}"
      }
     ]
    },
    {
     "title": "Contract",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 13, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "mSC" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_metrics_pricing_contract_price{instance=\"$hostdhost\"} / 1000000000000000000000"
      }
     ]
    },
    {
     "title": "Sector Access",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "SC / million" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_settings_sectoraccess_price{instance=\"$hostdhost\"} / 100000000000000000"
      }
     ]
    },
    {
     "title": "Base RPC",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 19, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "SC / million" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_settings_baserpc_price{instance=\"$hostdhost\"} / 100000000000000000"
      }
     ]
    },
    {
     "title": "Pricing",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 22, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "(hostd_settings_storage_price{instance=\"$hostdhost\"} * 43) / 10000000000",
       "legendFormat": "storage"
      },
      {
       "expr": "hostd_metrics_pricing_ingress_price{instance=\"$hostdhost\"} / 1000000000000",
       "legendFormat": "ingress"
      },
      {
       "expr": "hostd_metrics_pricing_egress_price{instance=\"$hostdhost\"} / 1000000000000",
       "legendFormat": "egress"
      },
      {
       "expr": "((hostd_settings_max_collateral{instance=\"$hostdhost\"} / 1000000000000000000000000) / 30) * 10",
       "legendFormat": "collateral"
      },
      {
       "expr": "hostd_metrics_pricing_contract_price{instance=\"$hostdhost\"} / 1000000000000000000000",
       "legendFormat": "contract"
      },
      {
       "expr": "hostd_settings_sectoraccess_price{instance=\"$hostdhost\"} / 100000000000000000",
       "legendFormat": "sector access"
      },
      {
       "expr": "hostd_settings_baserpc_price{instance=\"$hostdhost\"} / 100000000000000000",
       "legendFormat": "rpc"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Used",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_volume_used_sectors{instance=\"$hostdhost\"} / hostd_volume_total_sectors{instance=\"$hostdhost\"} * 100",
       "legendFormat": "{{ local_path }}"
      }
     ]
    },
    {
     "title": "Successful reads",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_volume_successful_reads{instance=\"$hostdhost\"}",
       "legendFormat": "{{ local_path }}"
      }
     ]
    },
    {
     "title": "Failed reads",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_volume_failed_reads{instance=\"$hostdhost\"}",
       "legendFormat": "{{ local_path }}"
      }
     ]
    },
    {
     "title": "Successful writes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_volume_successful_writes{instance=\"$hostdhost\"}",
       "legendFormat": "{{ local_path }}"
      }
     ]
    },
    {
     "title": "Failed writes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hostd_volume_failed_writes{instance=\"$hostdhost\"}",
       "legendFormat": "{{ local_path }}"
      }
     ]
    }
   ]
  }
 ]
}