# sia global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: hostd_api_state_host
    metrics_path: /api/state/host
    basic_auth:
      username: ''
      password: 'hostsarecool'
    params:
      response: [prometheus]
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_api_state_consensus
    metrics_path: /api/state/consensus
    basic_auth:
      username: ''
      password: 'hostsarecool'
    params:
      response: [prometheus]
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_api_syncer_address
    metrics_path: /api/syncer/address
    basic_auth:
      username: ''
      password: 'hostsarecool'
    params:
      response: [prometheus]
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_api_syncer_peers
    metrics_path: /api/syncer/peers
    basic_auth:
      username: ''
      password: 'hostsarecool'
    params:
      response: [prometheus]
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_api_alerts
    metrics_path: /api/alerts
    basic_auth:
      username: ''
      password: 'hostsarecool'
    params:
      response: [prometheus]
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_api_settings
    metrics_path: /api/settings
    basic_auth:
      username: ''
      password: 'hostsarecool'
    params:
      response: [prometheus]
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_api_metrics
    metrics_path: /api/metrics
    basic_auth:
      username: ''
      password: 'hostsarecool'
    params:
      response: [prometheus]
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_api_volumes
    metrics_path: /api/volumes
    basic_auth:
      username: ''
      password: 'hostsarecool'
    params:
      response: [prometheus]
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_api_sessions
    metrics_path: /api/sessions
    basic_auth:
      username: ''
      password: 'hostsarecool'
    params:
      response: [prometheus]
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_api_tpool_fee
    metrics_path: /api/tpool/fee
    basic_auth:
      username: ''
      password: 'hostsarecool'
    params:
      response: [prometheus]
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_api_wallet
    metrics_path: /api/wallet
    basic_auth:
      username: ''
      password: 'hostsarecool'
    params:
      response: [prometheus]
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_api_wallet_transactions
    metrics_path: /api/wallet/transactions
    basic_auth:
      username: ''
      password: 'hostsarecool'
    params:
      response: [prometheus]
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_api_wallet_pending
    metrics_path: /api/wallet/pending
    basic_auth:
      username: ''
      password: 'hostsarecool'
    params:
      response: [prometheus]
    static_configs:
      - targets:
        - hostd:9985

