# sia global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: hostd_state_host
    metrics_path: /prometheus/state/host
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - localhost:9880

  - job_name: hostd_state_consensus
    metrics_path: /prometheus/state/consensus
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - localhost:9880

  - job_name: hostd_syncer_address
    metrics_path: /prometheus/syncer/address
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - localhost:9880

  - job_name: hostd_syncer_peers
    metrics_path: /prometheus/syncer/peers
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - localhost:9880

  - job_name: hostd_alerts
    metrics_path: /prometheus/alerts
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - localhost:9880

  - job_name: hostd_settings
    metrics_path: /prometheus/settings
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - localhost:9880

  - job_name: hostd_metrics
    metrics_path: /prometheus/metrics
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - localhost:9880

  - job_name: hostd_accounts
    metrics_path: /prometheus/accounts
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - localhost:9880

  - job_name: hostd_volumes
    metrics_path: /prometheus/volumes
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - localhost:9880

  - job_name: hostd_sessions
    metrics_path: /prometheus/sessions
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - localhost:9880

  - job_name: hostd_tpool_fee
    metrics_path: /prometheus/tpool/fee
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - localhost:9880

  - job_name: hostd_wallet
    metrics_path: /prometheus/wallet
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - localhost:9880

  - job_name: hostd_wallet_transactions
    metrics_path: /prometheus/wallet/transactions
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - localhost:9880

  - job_name: hostd_wallet_pending
    metrics_path: /prometheus/wallet/pending
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - localhost:9880

