# sia global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: hostd_state_host
    metrics_path: /prometheus/state/host
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_state_consensus
    metrics_path: /prometheus/state/consensus
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_syncer_address
    metrics_path: /prometheus/syncer/address
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_syncer_peers
    metrics_path: /prometheus/syncer/peers
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_alerts
    metrics_path: /prometheus/alerts
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_settings
    metrics_path: /prometheus/settings
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_metrics
    metrics_path: /prometheus/metrics
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_accounts
    metrics_path: /prometheus/accounts
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_volumes
    metrics_path: /prometheus/volumes
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_sessions
    metrics_path: /prometheus/sessions
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_tpool_fee
    metrics_path: /prometheus/tpool/fee
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_wallet
    metrics_path: /prometheus/wallet
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_wallet_transactions
    metrics_path: /prometheus/wallet/transactions
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - hostd:9985

  - job_name: hostd_wallet_pending
    metrics_path: /prometheus/wallet/pending
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - hostd:9985

  - job_name: renterd_bus_alerts
    metrics_path: /prometheus/bus/alerts
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_buckets
    metrics_path: /prometheus/bus/buckets
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_consensus_network
    metrics_path: /prometheus/bus/consensus/network
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_consensus_state
    metrics_path: /prometheus/bus/consensus/state
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_contracts
    metrics_path: /prometheus/bus/contracts
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_contracts_prunable
    metrics_path: /prometheus/bus/contracts/prunable
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_hosts
    metrics_path: /prometheus/bus/hosts
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_hosts_allowlist
    metrics_path: /prometheus/bus/hosts/allowlist
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_hosts_blocklist
    metrics_path: /prometheus/bus/hosts/blocklist
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_hosts_scanning
    metrics_path: /prometheus/bus/hosts/scanning
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_params_gouging
    metrics_path: /prometheus/bus/params/gouging
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_params_upload
    metrics_path: /prometheus/bus/params/upload
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_slabbuffers
    metrics_path: /prometheus/bus/slabbuffers
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_search_objects
    metrics_path: /prometheus/bus/search/objects
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_settings
    metrics_path: /prometheus/bus/settings
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_state
    metrics_path: /prometheus/bus/state
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_stats_objects
    metrics_path: /prometheus/bus/stats/objects
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_syncer_address
    metrics_path: /prometheus/bus/syncer/address
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_syncer_peers
    metrics_path: /prometheus/bus/syncer/peers
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_txpool_recommendedfee
    metrics_path: /prometheus/bus/txpool/recommendedfee
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_txpool_transactions
    metrics_path: /prometheus/bus/txpool/transactions
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_wallet
    metrics_path: /prometheus/bus/wallet
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_wallet_outputs
    metrics_path: /prometheus/bus/wallet/outputs
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_wallet_pending
    metrics_path: /prometheus/bus/wallet/pending
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_bus_wallet_transactions
    metrics_path: /prometheus/bus/wallet/transactions
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: renterd_autopilot_state
    metrics_path: /prometheus/autopilot/state
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - renterd:9982

  - job_name: walletd_wallets_localhost_9982_mywallet_balance
    metrics_path: /prometheus/wallets/mywallet/balance
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - walletd:9982

  - job_name: walletd_wallets_localhost_9982_mywallet_events
    metrics_path: /prometheus/wallets/mywallet/events
    basic_auth:
      username: ''
      password: 'hostsarecool'
    params:
      offset: [0]
      limit: [100]
    static_configs:
      - targets:
        - walletd:9982

  - job_name: walletd_consensus_network
    metrics_path: /prometheus/consensus/network
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - walletd:9982

  - job_name: walletd_consensus_tip
    metrics_path: /prometheus/consensus/tip
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - walletd:9982

  - job_name: walletd_syncer_peers
    metrics_path: /prometheus/syncer/peers
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - walletd:9982

  - job_name: walletd_txpool_transactions
    metrics_path: /prometheus/txpool/transactions
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - walletd:9982

  - job_name: walletd_txpool_fee
    metrics_path: /prometheus/txpool/fee
    basic_auth:
      username: ''
      password: 'hostsarecool'
    static_configs:
      - targets:
        - walletd:9982
